apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/cmoreira-dev/gitops.istio.git
    targetRevision: main
    path: helm/istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true  # ESTA LINHA É A CHAVE
    ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jsonPointers:
            - /webhooks/0/failurePolicy
            - /webhooks/0/clientConfig/caBundle