istiod:
  global:
    istioNamespace: istio-system
  nodeSelector:
    kubernetes.io/arch: amd64

gateway:
  name: istio-ingress
  global:
    istioNamespace: istio-system
    hub: docker.io/istio
    tag: "1.29.1"
  service:
    type: NodePort
  autoscaling:
    enabled: false
  nodeSelector:
    kubernetes.io/arch: amd64

base: {}
